# Generated by Django 5.1.7 on 2025-03-07 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celebration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'About Us', 'verbose_name_plural': 'About Us'},
        ),
    ]
